apiVersion: v1
kind: Secret
metadata:
  name: credentials
  labels:
    app: app-05
    chart: '{{ .Chart.Name }}-{{ .Chart.Version }}'
    release: '{{ .Release.Name }}'
    heritage: '{{ .Release.Service }}'
type: Opaque
data:
  password: {{ .Values.password | b64enc }}
  password_db: {{ .Values.password_db | b64enc }}